modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/MinecraftForge/MinecraftForge/issues" # Change this to the link to your mod's issue tracker.
license = "${license}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
description = '''${description}'''
authors = "${author}"
logoFile = "${icon_path}"

[[mixins]]
config = "${id}-common.mixins.json"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"