modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${issue_tracker_url}" # Change this to the link to your mod's issue tracker.
license = "${license}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
description = '''${description}'''
authors = "${author}"
logoFile = "${icon_path}"

[[mixins]]
config = "${id}-common.mixins.json"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"